### ISSUE TITLE
Smoothscroll Exception with Latest Jetbrains & GFM Markdown Plugins

### ISSUE THREAD

**Issue by boucains** [hccampos/smooth-scroll-plugin#3]
Hi Hugo, 

I received the following error in Jetbrains PhpStorm 9.0.2 on Windows 8.1 x64 with all patches applied. I'm using a Microsoft Wireless Laser Mouse 6000 V2.0 with Microsoft Intellimouse drivers. The new Jetbrains Markdown support version is 8.0.0.20150924. The new GitHub Markdown plugin version is 0.1.6. My JAVA JRE version (just in case - I see some java code entries, but I don't think this matters) is V8 Update 60 build 1.8.0_60-b27.

I created an empty README.markdown file, whereupon the program threw the following error. 

Please let me know if I can help you in any way to find and squash this issue.

```
org.intellij.plugins.markdown.preview.MarkdownSplitEditor cannot be cast to com.intellij.openapi.fileEditor.TextEditor
java.lang.ClassCastException: org.intellij.plugins.markdown.preview.MarkdownSplitEditor cannot be cast to com.intellij.openapi.fileEditor.TextEditor
    at com.hccampos.smoothscroll.SmoothScrollMouseWheelListener.<init>(SmoothScrollMouseWheelListener.java:33)
    at com.hccampos.smoothscroll.FileEditorListener.fileOpened(FileEditorListener.java:17)
    at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:322)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:309)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:295)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:288)
    at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
    at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
    at com.sun.proxy.$Proxy83.fileOpened(Unknown Source)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$12$1.run(FileEditorManagerImpl.java:940)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$14$1.run(FileEditorManagerImpl.java:1016)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:672)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:656)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:626)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:108)
    at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Best Regards, 

Jack Cain

**Comment by sasquach** [comment]
Same error here. 
Webstorm 10.0.4 
Markdown support 8.0.0.20150929

**Comment by hccampos** [comment]
Please use https://github.com/opus1269/smooth-scroller instead.
