### ISSUE TITLE
ClassCastException: DatabaseTableFileEditor

### ISSUE THREAD

**Issue by siimsoni** [hccampos/smooth-scroll-plugin#6]
```
com.intellij.database.editor.DatabaseTableFileEditor cannot be cast to com.intellij.openapi.fileEditor.TextEditor
java.lang.ClassCastException: com.intellij.database.editor.DatabaseTableFileEditor cannot be cast to com.intellij.openapi.fileEditor.TextEditor
    at com.hccampos.smoothscroll.SmoothScrollMouseWheelListener.<init>(SmoothScrollMouseWheelListener.java:33)
    at com.hccampos.smoothscroll.FileEditorListener.fileOpened(FileEditorListener.java:17)
    at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:368)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:355)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:341)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:334)
    at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
    at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:223)
    at com.sun.proxy.$Proxy73.fileOpened(Unknown Source)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$13$1.run(FileEditorManagerImpl.java:957)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$15$1.run(FileEditorManagerImpl.java:1055)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:672)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:656)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.k(FocusManagerImpl.java:626)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:108)
    at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This error occurs in PHPStorm with the official database editor plugin. The database editor plugin is available in other flavours. There is a similar problem here:
https://github.com/Vektah/CodeGlance/issues/3

**Comment by siimsoni** [comment]
This pull request seems like it would fix it https://github.com/hccampos/smooth-scroll-plugin/pull/4
