### ISSUE TITLE
Crash in PHPStorm 2016.3

### ISSUE THREAD

**Issue by iraklisg** [hccampos/smooth-scroll-plugin#7]
**The error**

com.intellij.database.editor.DatabaseTableFileEditor cannot be cast to com.intellij.openapi.fileEditor.TextEditor

**More details**
 
com.intellij.database.editor.DatabaseTableFileEditor cannot be cast to com.intellij.openapi.fileEditor.TextEditor
java.lang.ClassCastException: com.intellij.database.editor.DatabaseTableFileEditor cannot be cast to com.intellij.openapi.fileEditor.TextEditor
	at com.hccampos.smoothscroll.SmoothScrollMouseWheelListener.<init>(SmoothScrollMouseWheelListener.java:33)
	at com.hccampos.smoothscroll.FileEditorListener.fileOpened(FileEditorListener.java:17)
	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:381)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:368)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:354)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:347)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
	at com.sun.proxy.$Proxy74.fileOpened(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.c(FileEditorManagerImpl.java:964)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$9$1.run(FileEditorManagerImpl.java:1057)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.b(FocusManagerImpl.java:646)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:630)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.h(FocusManagerImpl.java:600)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:482)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2493)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:462)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.a(ToolbarUpdater.java:108)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:93)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$4.showNotify(ActionToolbarImpl.java:995)
	at com.intellij.util.ui.update.UiNotifyConnector.showNotify(UiNotifyConnector.java:82)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$5.showNotify(ActionToolbarImpl.java:1003)
	at com.intellij.util.ui.update.UiNotifyConnector$1.run(UiNotifyConnector.java:60)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by hccampos** [comment]
Hi @iraklisg, I am not maintaining this extension anymore since I don't use WebStorm anymore. Use https://github.com/opus1269/smooth-scroller instead.

**Comment by iraklisg** [comment]
Ok @hccampos thank you for your suggestion
